# Generated by Django 3.0.8 on 2020-08-18 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20200815_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.TextField()),
                ('side', models.CharField(choices=[('N', 'Neutral'), ('F', 'For'), ('A', 'Against')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='argument',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='side',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(max_length=260, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='debate.Topic'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Followed_on',
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.AddField(
            model_name='follower',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Discussion'),
        ),
        migrations.AddField(
            model_name='follower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='argument',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_arguments', to='debate.Discussion'),
        ),
        migrations.AddField(
            model_name='argument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_arguments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussion',
            name='followers',
            field=models.ManyToManyField(related_name='following_topics', through='debate.Follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='follower',
            constraint=models.UniqueConstraint(fields=('user', 'discussion'), name='Follow_once'),
        ),
    ]
