# Generated by Django 3.0.8 on 2020-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_discussion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default=1, max_length=260),
            preserve_default=False,
        ),
    ]
