# Generated by Django 3.0.8 on 2020-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0006_auto_20200819_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(max_length=260, unique=True),
        ),
    ]
