# Generated by Django 3.0.8 on 2020-08-24 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_auto_20200822_1930'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='Like_once',
        ),
        migrations.RemoveField(
            model_name='like',
            name='discussion',
        ),
        migrations.AddField(
            model_name='like',
            name='argument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='debate.Argument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_arguments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'argument'), name='Like_once'),
        ),
    ]
